name       : python-sniffio
version    : 1.2.0
release    : 1
source     :
    - https://github.com/python-trio/sniffio/archive/v1.2.0.tar.gz : 0e9af48e3f55d286cac3884c4fd0f2c4365702a9ae447bf029d7fc9046c3d7a4
license    : Apache-2.0
component  : programming.python
summary    : Sniff out which async library your code is running under 
description: |
    Sniff out which async library your code is running under
build      : |
    %python3_setup
install    : |
    %python3_install
# Requires curio
#check      : |
#    %python3_test pytest3
