name       : python-sniffio
version    : 1.3.0
release    : 4
source     :
    - https://github.com/python-trio/sniffio/archive/refs/tags/v1.3.0.tar.gz : 9279dc8ca9a78186d14d5e5892c21bcf756381039997bf8f5d7ed90af884dda1
homepage   : https://github.com/python-trio/sniffio
license    : Apache-2.0
component  : programming.python
summary    : Sniff out which async library your code is running under
description: |
    Sniff out which async library your code is running under
build      : |
    %python3_setup
install    : |
    %python3_install
# Requires curio
#check      : |
#    %python3_test pytest3
